--Script SQL de Criação de Tabelas (DDL) — Sistema de Vendas
-- =====================================================================
-- SCRIPT DE IMPLANTAÇÃO DO BANCO DE DADOS (DDL)
-- SISTEMA DE VENDAS E ANÁLISE COMERCIAL
-- Compatível com Oracle Database 23ai / Oracle APEX
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. LIMPEZA DO AMBIENTE (OPCIONAL - EXECUTE SE QUISER RESETAR O SCHEMA)
-- ---------------------------------------------------------------------
DROP TABLE tb_auditoria_venda CASCADE CONSTRAINTS;
DROP TABLE tb_venda_item CASCADE CONSTRAINTS;
DROP TABLE tb_venda CASCADE CONSTRAINTS;
DROP TABLE tb_produto CASCADE CONSTRAINTS;
DROP TABLE tb_vendedor CASCADE CONSTRAINTS;
DROP TABLE tb_cliente CASCADE CONSTRAINTS;
DROP TABLE tb_categoria CASCADE CONSTRAINTS;
DROP TABLE tb_calendario CASCADE CONSTRAINTS;


-- ---------------------------------------------------------------------
-- 1. TABELA: TB_CATEGORIA [1]
-- ---------------------------------------------------------------------
CREATE TABLE tb_categoria (
    id_categoria  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(80) NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uq_tb_categoria_nome UNIQUE (nome)
);


-- ---------------------------------------------------------------------
-- 2. TABELA: TB_CLIENTE [2]
-- ---------------------------------------------------------------------
CREATE TABLE tb_cliente (
    id_cliente   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(120) NOT NULL,
    email        VARCHAR2(120) NOT NULL,
    cpf          VARCHAR2(11) NOT NULL,
    telefone     VARCHAR2(20),
    dt_cadastro  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_tb_cliente_email UNIQUE (email),
    CONSTRAINT uq_tb_cliente_cpf UNIQUE (cpf),
    CONSTRAINT ck_tb_cliente_ativo CHECK (ativo IN ('S', 'N'))
);


-- ---------------------------------------------------------------------
-- 3. TABELA: TB_VENDEDOR [3]
-- ---------------------------------------------------------------------
CREATE TABLE tb_vendedor (
    id_vendedor  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(120) NOT NULL,
    email        VARCHAR2(120) NOT NULL,
    dt_admissao  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_vendedor PRIMARY KEY (id_vendedor),
    CONSTRAINT uq_tb_vendedor_email UNIQUE (email),
    CONSTRAINT ck_tb_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);


-- ---------------------------------------------------------------------
-- 4. TABELA: TB_PRODUTO [2]
-- ---------------------------------------------------------------------
CREATE TABLE tb_produto (
    id_produto    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria  NUMBER NOT NULL,
    sku           VARCHAR2(30) NOT NULL,
    nome          VARCHAR2(120) NOT NULL,
    preco_unit    NUMBER(12,2) NOT NULL,
    ativo         CHAR(1) DEFAULT 'S' NOT NULL,
    dt_cadastro   DATE DEFAULT SYSDATE NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_produto PRIMARY KEY (id_produto),
    CONSTRAINT uq_tb_produto_sku UNIQUE (sku),
    CONSTRAINT fk_tb_produto_categoria FOREIGN KEY (id_categoria)
        REFERENCES tb_categoria (id_categoria),
    CONSTRAINT ck_tb_produto_preco CHECK (preco_unit > 0),
    CONSTRAINT ck_tb_produto_ativo CHECK (ativo IN ('S', 'N'))
);

-- Índice de Performance para FK de Produto [2]
CREATE INDEX ix_prod_categoria ON tb_produto (id_categoria);


-- ---------------------------------------------------------------------
-- 5. TABELA: TB_VENDA [2]
-- ---------------------------------------------------------------------
CREATE TABLE tb_venda (
    id_venda        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      NUMBER NOT NULL,
    id_vendedor     NUMBER NOT NULL,
    dt_venda        DATE DEFAULT SYSDATE NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    canal           VARCHAR2(20) NOT NULL,
    valor_bruto     NUMBER(14,2) DEFAULT 0 NOT NULL,
    desconto_total  NUMBER(14,2) DEFAULT 0 NOT NULL,
    valor_liquido   NUMBER(14,2) DEFAULT 0 NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_venda PRIMARY KEY (id_venda),
    CONSTRAINT fk_tb_venda_cliente FOREIGN KEY (id_cliente)
        REFERENCES tb_cliente (id_cliente),
    CONSTRAINT fk_tb_venda_vendedor FOREIGN KEY (id_vendedor)
        REFERENCES tb_vendedor (id_vendedor),
    CONSTRAINT ck_tb_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    CONSTRAINT ck_tb_venda_canal CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    CONSTRAINT ck_tb_venda_valores CHECK (valor_liquido >= 0)
);

-- Índices de Performance para Venda [3]
CREATE INDEX ix_venda_dt ON tb_venda (dt_venda);
CREATE INDEX ix_venda_cliente ON tb_venda (id_cliente);
CREATE INDEX ix_venda_vendedor ON tb_venda (id_vendedor);


-- ---------------------------------------------------------------------
-- 6. TABELA: TB_VENDA_ITEM [3]
-- ---------------------------------------------------------------------
CREATE TABLE tb_venda_item (
    id_item             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda            NUMBER NOT NULL,
    id_produto          NUMBER NOT NULL,
    quantidade          NUMBER(10) NOT NULL,
    preco_unit          NUMBER(12,2) NOT NULL,
    desconto_item       NUMBER(12,2) DEFAULT 0 NOT NULL,
    valor_total         NUMBER(14,2) NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_venda_item PRIMARY KEY (id_item),
    CONSTRAINT fk_tb_item_venda FOREIGN KEY (id_venda)
        REFERENCES tb_venda (id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_tb_item_produto FOREIGN KEY (id_produto)
        REFERENCES tb_produto (id_produto),
    CONSTRAINT ck_tb_item_qtd CHECK (quantidade > 0),
    CONSTRAINT ck_tb_item_preco CHECK (preco_unit >= 0),
    CONSTRAINT ck_tb_item_desconto CHECK (desconto_item >= 0)
);

-- Índices de Performance para Itens de Venda [3]
CREATE INDEX ix_item_venda ON tb_venda_item (id_venda);
CREATE INDEX ix_item_produto ON tb_venda_item (id_produto);


-- ---------------------------------------------------------------------
-- 7. TABELA EXTRA/BONUS: TB_AUDITORIA_VENDA [1]
-- ---------------------------------------------------------------------
CREATE TABLE tb_auditoria_venda (
    id_auditoria  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda      NUMBER NOT NULL,
    operacao      VARCHAR2(10) NOT NULL,
    usuario_bd    VARCHAR2(128) NOT NULL,
    dt_evento     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detalhes      VARCHAR2(4000),
    -- Constraints
    CONSTRAINT pk_tb_auditoria_venda PRIMARY KEY (id_auditoria)
);


-- ---------------------------------------------------------------------
-- 8. TABELA EXTRA/BONUS: TB_CALENDARIO [1]
-- ---------------------------------------------------------------------
CREATE TABLE tb_calendario (
    dt_ref            DATE NOT NULL,
    ano               NUMBER(4) NOT NULL,
    mes               NUMBER(2) NOT NULL,
    dia               NUMBER(2) NOT NULL,
    trimestre         NUMBER(1) NOT NULL,
    nome_mes          VARCHAR2(15) NOT NULL,
    dia_semana        NUMBER(1) NOT NULL,
    nome_dia_semana   VARCHAR2(15) NOT NULL,
    -- Constraints
    CONSTRAINT pk_tb_calendario PRIMARY KEY (dt_ref)
);