CREATE TABLE TB_CLIENTE (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    cpf VARCHAR2(11),
    ativo VARCHAR2(1) DEFAULT 'S',

    CONSTRAINT pk_tb_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_tb_cliente_email UNIQUE (email),
    CONSTRAINT uq_tb_cliente_cpf UNIQUE (cpf),
    CONSTRAINT ck_tb_cliente_ativo CHECK (ativo IN ('S','N'))
);

CREATE TABLE TB_VENDEDOR (
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    ativo VARCHAR2(1) DEFAULT 'S',

    CONSTRAINT pk_tb_vendedor PRIMARY KEY (id_vendedor),
    CONSTRAINT uq_tb_vendedor_email UNIQUE (email),
    CONSTRAINT ck_tb_vendedor_ativo CHECK (ativo IN ('S','N'))
);

CREATE TABLE TB_CATEGORIA (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,

    CONSTRAINT pk_tb_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE TB_PRODUTO (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria NUMBER NOT NULL,
    sku VARCHAR2(50) NOT NULL,
    nome VARCHAR2(150) NOT NULL,
    preco_unit NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_tb_produto PRIMARY KEY (id_produto),
    CONSTRAINT fk_tb_produto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES tb_categoria(id_categoria),
    CONSTRAINT uq_tb_produto_sku UNIQUE (sku),
    CONSTRAINT ck_tb_produto_preco CHECK (preco_unit > 0)
);

CREATE TABLE TB_VENDA (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    id_vendedor NUMBER NOT NULL,
    dt_venda DATE DEFAULT SYSDATE,
    valor_liquido NUMBER(10,2),
    canal VARCHAR2(20),
    status VARCHAR2(20),

    CONSTRAINT pk_tb_venda PRIMARY KEY (id_venda),

    CONSTRAINT fk_tb_venda_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES tb_cliente(id_cliente),

    CONSTRAINT fk_tb_venda_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES tb_vendedor(id_vendedor),

    CONSTRAINT ck_tb_venda_canal
        CHECK (canal IN ('APP','SITE','LOJA','TELEFONE')),

    CONSTRAINT ck_tb_venda_status
        CHECK (status IN ('ABERTA','FECHADA','CANCELADA'))
);

CREATE TABLE TB_VENDA_ITEM (
    id_venda_item NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER NOT NULL,
    valor_unit NUMBER(10,2) NOT NULL,
    percentual_desconto NUMBER DEFAULT 0,
    valor_total NUMBER(10,2),

    CONSTRAINT pk_tb_venda_item PRIMARY KEY (id_venda_item),

    CONSTRAINT fk_tb_venda_item_venda
        FOREIGN KEY (id_venda)
        REFERENCES tb_venda(id_venda)
        ON DELETE CASCADE,

    CONSTRAINT fk_tb_venda_item_produto
        FOREIGN KEY (id_produto)
        REFERENCES tb_produto(id_produto),

    CONSTRAINT ck_tb_venda_item_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT ck_tb_venda_item_desconto
        CHECK (percentual_desconto BETWEEN 0 AND 50)
);