/*EXERCÍCIOS PRÁTICOS - Atividade Prática 03 - Consultas
Isabela de Oliveira athayde - 5SBD
SIMPLES
*/
---1- 
SELECT NOME, EMAIL, TELEFONE
FROM TB_CLIENTE
WHERE ATIVO = 'S'
ORDER BY NOME

---2- 
SELECT ID_VENDA, DT_VENDA, VALOR_LIQUIDO
FROM TB_VENDA
WHERE CANAL = 'APP'
AND STATUS = 'FECHADA'

---3- 
SELECT P.NOME PRODUTO, P.SKU, C.NOME CATEGORIA
FROM TB_PRODUTO P
JOIN TB_CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA

---4- 
SELECT COUNT(*)
FROM TB_VENDEDOR;

---5- 
SELECT NOME, PRECO_UNIT
FROM TB_PRODUTO
WHERE ATIVO = 'S'
ORDER BY PRECO_UNIT DESC

---****************************
---INTERMEDIÁRIO

---1-
 SELECT CANAL, SUM(VALOR_LIQUIDO)
FROM TB_VENDA
WHERE STATUS = 'FECHADA'
GROUP BY CANAL
ORDER BY SUM(VALOR_LIQUIDO) DESC

---2-
 SELECT V.NOME,
ROUND(AVG(VD.VALOR_LIQUIDO), 2) TICKET_MEDIO
FROM TB_VENDEDOR V
JOIN TB_VENDA VD
ON V.ID_VENDEDOR = VD.ID_VENDEDOR
WHERE VD.STATUS = 'FECHADA'
GROUP BY V.NOME

---3-
SELECT C.NOME, C.EMAIL
FROM TB_CLIENTE C
WHERE NOT EXISTS (
SELECT 1
FROM TB_VENDA VN
WHERE VN.ID_CLIENTE = C.ID_CLIENTE
)

---4-
SELECT VD.ID_VENDA, C.NOME, VD.VALOR_LIQUIDO
FROM TB_CLIENTE C
JOIN TB_VENDA VD
ON C.ID_CLIENTE = VD.ID_CLIENTE
WHERE VD.STATUS = 'FECHADA'
AND VD.VALOR_LIQUIDO > (
    SELECT AVG(VALOR_LIQUIDO)
    FROM TB_VENDA
    WHERE STATUS = 'FECHADA'
)

---5-
 SELECT NOME,
      PRECO_UNIT,
      CASE
         WHEN PRECO_UNIT < 50 THEN 'BARATO'
         WHEN PRECO_UNIT > 200 THEN 'CARO'
         ELSE 'MEDIO'
      END FAIXA_PRECO
FROM TB_PRODUTO

---****************************
---NIVEL AVANÇADO

---1- 
SELECT C.NOME,
      VD.DT_VENDA,
      VD.VALOR_LIQUIDO,
      ROW_NUMBER() OVER (
          PARTITION BY C.ID_CLIENTE
          ORDER BY VD.DT_VENDA
      ) NUMERO_COMPRA
FROM TB_CLIENTE C
JOIN TB_VENDA VD
ON C.ID_CLIENTE = VD.ID_CLIENTE

---2- 
SELECT VD.NOME,
      SUM(VN.VALOR_LIQUIDO) FATURAMENTO_TOTAL,
      ROUND(
          SUM(VN.VALOR_LIQUIDO) * 100 /
          SUM(SUM(VN.VALOR_LIQUIDO)) OVER (),
          2
      ) PERCENTUAL
FROM TB_VENDA VN
JOIN TB_VENDEDOR VD
ON VN.ID_VENDEDOR = VD.ID_VENDEDOR
WHERE VN.STATUS = 'FECHADA'
GROUP BY VD.NOME

---3- 
WITH VENDAS_MES AS (
   SELECT TRUNC(V.DT_VENDA, 'MM') MES_REFERENCIA,
          VD.NOME,
          SUM(V.VALOR_LIQUIDO) RECEITA_TOTAL
   FROM TB_VENDA V
   JOIN TB_VENDEDOR VD
   ON V.ID_VENDEDOR = VD.ID_VENDEDOR
   GROUP BY TRUNC(V.DT_VENDA, 'MM'), VD.NOME
)
SELECT MES_REFERENCIA,
      NOME,
      RECEITA_TOTAL,
      DENSE_RANK() OVER (
          PARTITION BY MES_REFERENCIA
          ORDER BY RECEITA_TOTAL DESC
      ) POSICAO_RANKING
FROM VENDAS_MES

---4-
SELECT ID_VENDA,
VALOR_LIQUIDO,
ROUND(VALOR_LIQUIDO - AVG(VALOR_LIQUIDO),2) OVER ()
DIFERENCA_PARA_MEDIA
FROM TB_VENDA;

--- 5-

WITH TOTAL_PRODUTOS AS (
   SELECT P.ID_PRODUTO,
          P.NOME,
          SUM(VI.QUANTIDADE) TOTAL_VENDIDO
   FROM TB_VENDA_ITEM VI
   JOIN TB_PRODUTO P
   ON VI.ID_PRODUTO = P.ID_PRODUTO
   GROUP BY P.ID_PRODUTO, P.NOME
), RANKING_PRODUTOS AS (
   SELECT ID_PRODUTO,
          NOME,
          TOTAL_VENDIDO,
          DENSE_RANK() OVER (
              ORDER BY TOTAL_VENDIDO DESC
          ) RANKING
   FROM TOTAL_PRODUTOS
) SELECT ID_PRODUTO,
      NOME,
      TOTAL_VENDIDO
FROM RANKING_PRODUTOS
WHERE RANKING <= 3
